### PR TITLE
Fix: UTC time for inwords/InWords#171

### PR DESCRIPTION
**Pull request by SGmuwa**

### CODE REVIEW

**Comment by SGmuwa** [comment]
I resolved the conflict (46eb8007d3db1c032476dee5fef2306f21d418d4), but why did it appear?

**Comment by SGmuwa** [comment]
Why did I get [two crosses](https://github.com/inwords/InWords/pull/172/checks?check_run_id=499756862)? I did not touch other services.

**Comment by Alword** [comment]
It will be hard for me to look for errors if the time is recorded in UTC. While there is only one server and only one developer, it is quite convenient to use Moscow time.

**Comment by SGmuwa** [comment]
For the same reason, we might communicate in Russian, because all developers and users are Muscovites.

**Comment by Alword** [comment]
We use an international language because of github.

**Pull request closed without merging**
